
services:
  # Next.js Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/storage.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - MASTRA_BASE_URL=http://mastra:4111
    volumes:
      - app_data:/app/data
    depends_on:
      - mastra
    networks:
      - tasc_network

  # Mastra Backend Service
  mastra:
    build:
      context: .
      dockerfile: Dockerfile.mastra
    ports:
      - "4111:4111"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/data/storage.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
    volumes:
      - app_data:/app/data
      - ./src/mastra:/app/src/mastra
    networks:
      - tasc_network

  # Deep Research Agent Service
  deep-research:
    build:
      context: ./tasc-deep-research-agent
      dockerfile: ../Dockerfile.deep-research
    ports:
      - "4112:4111"
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EXA_API_KEY=${EXA_API_KEY}
    volumes:
      - research_data:/app/data
      - ./tasc-deep-research-agent/src:/app/src
    networks:
      - tasc_network

volumes:
  app_data:
    driver: local
  research_data:
    driver: local

networks:
  tasc_network:
    driver: bridge